package org.joshdb.ThinDFA;

import gnu.trove.map.hash.TCharIntHashMap;

/**
 * Created by josh.hight on 9/25/17.
 */
public class EssentialMedicationsDFA extends UnionDFA
{
    private static final String[] essentialMedications = new String[] {
            "BCG vaccine",
            "HPV vaccine",
            "Haemophilus influenzae type b vaccine",
            "Japanese encephalitis vaccine",
            "Lugol's solution",
            "abacavir",
            "ABC",
            "acetazolamide",
            "acetic acid",
            "acetylcysteine",
            "acetylsalicylic acid",
            "aciclovir",
            "albendazole",
            "alcohol based hand rub",
            "all-trans retinoic acid",
            "ATRA",
            "allopurinol",
            "amidotrizoate",
            "amikacin",
            "amiloride",
            "amiodarone",
            "amitriptyline",
            "amlodipine",
            "amodiaquine",
            "amoxicillin",
            "amphotericin B",
            "ampicillin",
            "anti-D immunoglobulin",
            "antitetanus immunoglobulin",
            "antivenom immunoglobulin",
            "artemether",
            "artesunate",
            "ascorbic acid",
            "asparaginase",
            "atazanavir",
            "atracurium",
            "atropine",
            "azathioprine",
            "azithromycin",
            "aztreonam",
            "barium sulfate",
            "beclometasone",
            "bedaquiline",
            "bendamustine",
            "benzathine benzylpenicillin",
            "benznidazole",
            "benzoyl peroxide",
            "benzyl benzoate",
            "benzylpenicillin",
            "betamethasone",
            "bevacizumab",
            "bicalutamide",
            "biperiden",
            "bisoprolol",
            "bleomycin",
            "budesonide",
            "bupivacaine",
            "caffeine citrate",
            "calamine",
            "calcium",
            "capecitabine",
            "capreomycin",
            "carbamazepine",
            "carbidopa",
            "carboplatin",
            "cefalexin",
            "cefazolin",
            "cefepime",
            "cefixime",
            "cefotaxime",
            "ceftaroline",
            "ceftazidime",
            "ceftriaxone",
            "charcoal activated",
            "chlorambucil",
            "chloramphenicol",
            "chlorhexidine",
            "chlorine base compound",
            "chloroquine",
            "chloroxylenol",
            "chlorpromazine",
            "cholera vaccine",
            "ciclosporin",
            "ciprofloxacin",
            "cisplatin",
            "clarithromycin",
            "clavulanic acid",
            "clindamycin",
            "clofazimine",
            "clomifene",
            "clomipramine",
            "clopidogrel",
            "clotrimazole",
            "cloxacillin",
            "clozapine",
            "coagulation factor IX",
            "coagulation factor VIII",
            "coal tar",
            "codeine",
            "colecalciferol",
            "colistin",
            "condoms",
            "copper-containing device",
            "cyclizine",
            "cyclophosphamide",
            "cycloserine",
            "cytarabine",
            "dacarbazine",
            "daclatasvir",
            "dactinomycin",
            "dapsone",
            "daptomycin",
            "darunavir",
            "dasabuvir",
            "dasatinib",
            "daunorubicin",
            "deferoxamine",
            "delamanid",
            "desmopressin",
            "dexamethasone",
            "dextran",
            "diaphragms",
            "diazepam",
            "diethylcarbamazine",
            "digoxin",
            "dihydroartemisinin",
            "diloxanide",
            "dimercaprol",
            "diphtheria antitoxin",
            "diphtheria vaccine",
            "docetaxel",
            "docusate sodium",
            "dolutegravir",
            "dopamine",
            "doxorubicin",
            "doxycycline",
            "efavirenz",
            "EFV",
            "EFZ",
            "eflornithine",
            "emtricitabine",
            "enalapril",
            "enoxaparin",
            "entecavir",
            "ephedrine",
            "epinephrine",
            "adrenaline",
            "ergocalciferol",
            "ergometrine",
            "erythromycin",
            "erythropoiesis-stimulating agents",
            "estradiol cypionate",
            "ethambutol",
            "ethanol",
            "ethinylestradiol",
            "ethionamide",
            "ethosuximide",
            "etonogestrel-releasing implant",
            "etoposide",
            "fentanyl",
            "ferrous salt",
            "fifth generation cephalosporins",
            "filgrastim",
            "fluconazole",
            "flucytosine",
            "fludarabine",
            "fludrocortisone",
            "fluorescein",
            "fluorouracil",
            "fluoxetine",
            "fluphenazine",
            "folic acid",
            "fomepizole",
            "formoterol",
            "fosfomycin",
            "fourth generation cephalosporins",
            "fresh frozen plasma",
            "furosemide",
            "gemcitabine",
            "gentamicin",
            "gliclazide",
            "glucagon",
            "glucose",
            "glutaral",
            "glyceryl trinitrate",
            "griseofulvin",
            "haloperidol",
            "halothane",
            "heparin sodium",
            "hepatitis A vaccine",
            "hepatitis B vaccine",
            "hydralazine",
            "hydrochlorothiazide",
            "hydrocortisone",
            "hydroxocobalamin",
            "hydroxycarbamide",
            "hydroxychloroquine",
            "hyoscine butylbromide",
            "hyoscine hydrobromide",
            "ibuprofen",
            "ifosfamide",
            "imatinib",
            "influenza vaccine",
            "insulin",
            "intermediate-acting insulin",
            "intraperitoneal dialysis solution",
            "iohexol",
            "ipratropium bromide",
            "irinotecan",
            "isoflurane",
            "isoniazid",
            "isosorbide dinitrate",
            "itraconazole",
            "ivermectin",
            "kanamycin",
            "ketamine",
            "lactulose",
            "lamivudine",
            "TC",
            "lamotrigine",
            "latanoprost",
            "ledipasvir",
            "leuprorelin",
            "levamisole",
            "levodopa",
            "levofloxacin",
            "levonorgestrel",
            "levothyroxine",
            "lidocaine",
            "linezolid",
            "lithium carbonate",
            "loperamide",
            "lopinavir",
            "loratadine",
            "lorazepam",
            "losartan",
            "lumefantrine",
            "magnesium sulfate",
            "mannitol",
            "measles vaccine",
            "mebendazole",
            "medroxyprogesterone acetate",
            "mefloquine",
            "meglumine iotroxate",
            "melarsoprol",
            "meningococcal meningitis vaccine",
            "mercaptopurine",
            "meropenem",
            "mesna",
            "metformin",
            "methadone",
            "methotrexate",
            "methyldopa",
            "methylprednisolone",
            "methylthioninium chloride",
            "methylene blue",
            "metoclopramide",
            "metronidazole",
            "miconazole",
            "midazolam",
            "mifepristone",
            "miltefosine",
            "misoprostol",
            "morphine",
            "moxifloxacin",
            "mumps vaccine",
            "mupirocin",
            "naloxone",
            "natamycin",
            "neostigmine",
            "nevirapine",
            "NVP",
            "niclosamide",
            "nicotinamide",
            "nicotine replacement therapy",
            "NRT",
            "nifedipine",
            "nifurtimox",
            "nilotinib",
            "nitrofurantoin",
            "nitrous oxide",
            "norethisterone",
            "normal immunoglobulin",
            "nystatin",
            "ofloxacin",
            "ombitasvir",
            "omeprazole",
            "ondansetron",
            "oral rehydration salts",
            "oseltamivir",
            "oxaliplatin",
            "oxamniquine",
            "oxazolindinones",
            "oxygen",
            "oxytocin",
            "p-aminosalicylic acid",
            "packed red blood cells",
            "paclitaxel",
            "pancreatic enzymes",
            "paracetamol",
            "paritaprevir",
            "paromomycin",
            "pegylated interferon alfa a",
            "penicillamine",
            "pentamidine",
            "permethrin",
            "pertussis vaccine",
            "phenobarbital",
            "phenoxymethylpenicillin",
            "phenytoin",
            "phytomenadione",
            "pilocarpine",
            "piperacillin",
            "piperaquine phosphate",
            "platelet concentrates",
            "pneumococcal vaccine",
            "podophyllum resin",
            "poliomyelitis vaccine",
            "polymyxins",
            "potassium chloride",
            "potassium ferric hexacyano-ferrate",
            "Prussian blue",
            "potassium iodide",
            "potassium permanganate",
            "povidone iodine",
            "praziquantel",
            "prednisolone",
            "primaquine",
            "procaine benzylpenicillin",
            "procarbazine",
            "progesterone vaginal ring",
            "proguanil",
            "propofol",
            "propranolol",
            "propylthiouracil",
            "prostaglandin E",
            "protamine sulfate",
            "pyrantel",
            "pyrazinamide",
            "pyridostigmine",
            "pyridoxine",
            "pyrimethamine",
            "pyronaridine tetraphosphate",
            "quinine",
            "rabies immunoglobulin",
            "rabies vaccine",
            "raltegravir",
            "ranitidine",
            "retinol",
            "ribavirin",
            "riboflavin",
            "rifabutin",
            "rifampicin",
            "rifapentine",
            "risperidone",
            "ritonavir",
            "ritonavir",
            "LPV/r",
            "rituximab",
            "rotavirus vaccine",
            "rubella vaccine",
            "salbutamol",
            "salicylic acid",
            "selenium sulfide",
            "senna",
            "silver sulfadiazine",
            "simeprevir",
            "simvastatin",
            "sodium calcium edetate",
            "sodium chloride",
            "sodium fluoride",
            "sodium hydrogen carbonate",
            "sodium lactate",
            "sodium nitrite",
            "sodium nitroprusside",
            "sodium stibogluconate",
            "meglumine antimoniate",
            "sodium thiosulfate",
            "sofosbovir",
            "sofosbuvir",
            "spectinomycin",
            "spironolactone",
            "streptokinase",
            "streptomycin",
            "succimer",
            "sulfadiazine",
            "sulfadoxine",
            "sulfamethoxazole",
            "sulfasalazine",
            "suramin sodium",
            "surfactant",
            "suxamethonium",
            "tamoxifen",
            "tazobactam",
            "tenofovir disoproxil fumarate",
            "terbinafine",
            "testosterone",
            "tetanus vaccine",
            "tetracaine",
            "tetracycline",
            "thiamine",
            "thioguanine",
            "tick-borne encephalitis vaccine",
            "tigecycline",
            "timolol",
            "tranexamic acid",
            "trastuzumab",
            "triclabendazole",
            "trimethoprim",
            "tropicamide",
            "tuberculin purified protein derivative",
            "PPD",
            "typhoid vaccine",
            "ulipristal",
            "urea",
            "valganciclovir",
            "valproic acid",
            "sodium valproate",
            "vancomycin",
            "varicella vaccine",
            "vecuronium",
            "velpatasvir",
            "verapamil",
            "vinblastine",
            "vincristine",
            "vinorelbine",
            "voriconazole",
            "warfarin",
            "water for injection",
            "whole blood",
            "xylometazoline",
            "yellow fever vaccine",
            "zidovudine",
            "zidovudine",
            "ZDV",
            "AZT",
            "zinc sulfate",
            "zoledronic acid",
    };

    public EssentialMedicationsDFA() throws IncompatibleRegexException
    {
        super(essentialMedications);
    }
}
